export default function learnpage() {
    return (
        <section className="h-screen bg-gray-100 flex gap-4"> 
    <div className="bg-purple-300 p-6 h-55 w-68 rounded-4xl flex flex-col justify-between text-blue-950">
        <div className="flex gap-2 font-bold">
            <img src="/palette.svg" alt="Client detail"/>
                <p>Client details</p>
        </div>
        <div>
            <h2 className="text-3xl font-bold">Cornelius Greenfelder</h2>
            <p className="font-bold">8 velifiend</p>
            </div>
            </div> 

    <div className="bg-purple-300 p-6 h-55 w-68 rounded-4xl flex flex-col justify-between text-blue-200">
        <div className="flex gap-2 font-bold">
            <img src="/palette.svg" alt="Client detail"/>
                <p>Projects</p>
            </div>
        <div/>

         <div>
            <h3 className="text-3xl font-bold">Ongoing</h3>
            <p className="font-bold">2 ($3.8k)</p>
            </div>
 
    <div className="bg-purple-300 p-6 h-55 w-68 rounded-4xl flex flex-col justify-between text-blue-200">
        <div className="flex gap-2 font-bold">
            <img src="/palette.svg" alt="Client detail"/>
            
        <div className="text-3x4 font-bold">location
        <div className="text-3x4 font-bold">United States, New York
        <div className="text-3x4 font-bold">With Us
        <div className="text-3x4 font-bold">6 Jan 2024

        <div/> 
        </div>
         </div>   
        </div>
            </div> 

            </div>

            </section>
     )
}